
#设置tomcat服务端口号
server:
  port: 1113

#设置服务名称
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost3
  client:
    #注册中心不需要注册自己
    register-with-eureka: true
    #注册中心不需要去发现服务
    fetch-registry: true
    #设置服务注册中心的URL
    serviceUrl:
      defaultZone: http://localhost1:1111/eureka,http://localhost2:1112/eureka
